version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  
  build:
    commands:
      - npm run build
      - echo ${env.WEBSITE_BUCKET_NAME}
      - echo 'TEST'
      - echo $env.WEBSITE_BUCKET_NAME
      - echo env.$TEST_VARIABLE
      - echo 'Another'
      - echo env.${$TEST_VARIABLE}
  
  post_build:
    commands:
      - aws s3 cp --recursive ./build s3://${WEBSITE_BUCKET_NAME}/
      # - aws cloudfront create-invalidation --distribution-id E3I1XNMUPGTK9K --path /\*
